const SUPABASE_URL="https://jjwqdvjtcorzpvxlfnog.supabase.co",SUPABASE_KEY="sb_publishable_J4NQfjyOIj_sMUA53iSnVA_inPdNLZ7";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),demoScripts=[
{id:"demo-1",title:"Blox Fruits — Universal Hub",game:"Blox Fruits",tags:["Universal","Farm","PvP"],author:"ScriptDepo",views:18420,likes:932,verified:true,desc:"Blox Fruits için topluluk tarafından paylaşılan yardımcı script koleksiyonu.",code:"-- ScriptDepo demo\nprint('Blox Fruits script')"},
{id:"demo-2",title:"MM2 Utility Pack",game:"MM2",tags:["MM2","Utility"],author:"ScriptDepo",views:12100,likes:701,verified:true,desc:"MM2 için çeşitli utility özelliklerini tek yerde toplar.",code:"-- ScriptDepo demo\nprint('MM2 utility')"},
{id:"demo-3",title:"Universal ESP Toolkit",game:"Universal",tags:["Universal","ESP"],author:"ScriptDepo",views:9800,likes:540,verified:false,desc:"Uyumlu deneyimlerde görsel yardımcı özellikler için topluluk paylaşımı.",code:"-- ScriptDepo demo\nprint('Universal toolkit')"},
{id:"demo-4",title:"Brookhaven Tools",game:"Brookhaven",tags:["Brookhaven","Fun"],author:"ScriptDepo",views:7300,likes:420,verified:false,desc:"Brookhaven topluluğundan araç ve eğlence odaklı paylaşım.",code:"-- ScriptDepo demo\nprint('Brookhaven tools')"},
{id:"demo-5",title:"Blade Ball Helper",game:"Blade Ball",tags:["Blade Ball","Utility"],author:"ScriptDepo",views:6500,likes:318,verified:true,desc:"Blade Ball için topluluk tarafından gönderilmiş yardımcı script.",code:"-- ScriptDepo demo\nprint('Blade Ball helper')"},
{id:"demo-6",title:"Adopt Me Toolkit",game:"Adopt Me",tags:["Adopt Me","Tools"],author:"ScriptDepo",views:4900,likes:205,verified:false,desc:"Adopt Me topluluğundan araç koleksiyonu.",code:"-- ScriptDepo demo\nprint('Adopt Me toolkit')"}];
let scripts=[...demoScripts],sort="popular",filter="",user=null,authMode="login";
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),fmt=n=>n>=1000?(n/1000).toFixed(1)+"K":n;
function render(){let q=(search.value||"").toLowerCase(),list=scripts.filter(s=>(!filter||s.game===filter||s.tags.includes(filter))&&(!q||[s.title,s.game,s.author,s.desc,...s.tags].join(" ").toLowerCase().includes(q)));if(sort==="new")list=[...list].reverse();if(sort==="views")list.sort((a,b)=>b.views-a.views);if(sort==="popular")list.sort((a,b)=>b.likes-a.likes);grid.innerHTML=list.map(card).join("")||'<div class="card"><h3>Sonuç bulunamadı</h3><p class="desc">Başka bir oyun veya etiket deneyin.</p></div>';statScripts.textContent=list.length;statViews.textContent=fmt(list.reduce((a,s)=>a+s.views,0))}
function card(s){return '<article class="card"><div class="card-top"><div class="icon">⚡</div><span class="verified">'+(s.verified?"✓ Doğrulandı":"")+'</span></div><h3>'+esc(s.title)+'</h3><p class="desc">'+esc(s.desc)+'</p><div class="meta"><span class="tag">'+esc(s.game)+'</span>'+s.tags.slice(0,3).map(t=>'<span class="tag">#'+esc(t)+'</span>').join("")+'</div><div class="card-foot"><span>👁 '+fmt(s.views)+' · ♥ '+fmt(s.likes)+'</span><button onclick="openScript(\''+s.id+'\')">Detay →</button></div></article>'}
async function openScript(id){let s=scripts.find(x=>String(x.id)===String(id));if(!s)return;let comments=[];if(!String(id).startsWith("demo-")){let r=await db.from("comments").select("body,created_at").eq("script_id",id).order("created_at",{ascending:false});comments=r.data||[]}modalBox.innerHTML='<button class="close" onclick="hideModal()">×</button><span class="eyebrow">'+esc(s.game)+'</span><h2>'+esc(s.title)+'</h2><p class="desc">'+esc(s.desc)+'</p><p>👤 '+esc(s.author)+' · 👁 '+fmt(s.views)+' · ♥ '+fmt(s.likes)+'</p><div class="meta">'+s.tags.map(t=>'<span class="tag">#'+esc(t)+'</span>').join("")+'</div><pre class="code">'+esc(s.code)+'</pre><div class="detail-actions"><button class="primary" onclick="copyScript(\''+s.id+'\')">Kodu Kopyala</button>'+(!String(id).startsWith("demo-")?'<button class="ghost" onclick="likeScript(\''+s.id+'\')">♥ Beğen</button><button class="ghost" onclick="favoriteScript(\''+s.id+'\')">★ Favori</button>':'')+'</div><div class="comments"><h3>Yorumlar</h3>'+comments.map(c=>'<div class="comment"><b>Topluluk üyesi</b><p>'+esc(c.body)+'</p></div>').join("")+'<textarea id="commentText" placeholder="Yorumunu yaz..."></textarea><button class="primary" onclick="addComment(\''+s.id+'\')">Yorum gönder</button></div>';modal.classList.add("show")}
function copyScript(id){let s=scripts.find(x=>String(x.id)===String(id));navigator.clipboard?.writeText(s.code).then(()=>alert("Script kopyalandı!"))}function hideModal(){modal.classList.remove("show")}function closeModal(e){if(e.target.id==="modal")hideModal()}function setFilter(x){filter=x;search.value=x;document.getElementById("scripts").scrollIntoView({behavior:"smooth"});render()}function setSort(x,b){sort=x;document.querySelectorAll(".filters button").forEach(y=>y.classList.remove("active"));b.classList.add("active");render()}function toggleTheme(){document.body.classList.toggle("light")}
function openAuth(){auth.classList.add("show")}function hideAuth(){auth.classList.remove("show")}function toggleAuthMode(){authMode=authMode==="login"?"signup":"login";authTitle.textContent=authMode==="login"?"Giriş yap":"Kayıt ol";authSubmit.textContent=authMode==="login"?"Giriş Yap":"Kayıt Ol";authName.classList.toggle("hidden",authMode==="login")}
async function submitAuth(e){e.preventDefault();let r=authMode==="login"?await db.auth.signInWithPassword({email:authEmail.value,password:authPassword.value}):await db.auth.signUp({email:authEmail.value,password:authPassword.value,options:{data:{display_name:authName.value}}});authStatus.textContent=r.error?r.error.message:(authMode==="login"?"Giriş başarılı!":"Kayıt başarılı. E-postanı doğrula.");if(!r.error&&authMode==="login")hideAuth()}
async function publish(e){e.preventDefault();if(!user)return openAuth();let r=await db.from("scripts").insert({title:pTitle.value,slug:pTitle.value.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now(),game_name:pGame.value,tags:pTags.value.split(",").map(x=>x.trim()).filter(Boolean),description:"Topluluk tarafından gönderildi.",script_content:pCode.value,author_id:user.id,status:"pending"});if(r.error)return alert(r.error.message);e.target.reset();await loadDB();alert("Script gönderildi. Admin onayından sonra yayınlanacak.")}
async function likeScript(id){if(!user)return openAuth();let r=await db.from("script_likes").insert({script_id:id,user_id:user.id});if(r.error&&r.error.code!=="23505")return alert(r.error.message);await loadDB();openScript(id)}
async function favoriteScript(id){if(!user)return openAuth();let r=await db.from("favorites").insert({script_id:id,user_id:user.id});if(r.error&&r.error.code!=="23505")return alert(r.error.message);alert("Favorilere eklendi.")}
async function addComment(id){if(!user)return openAuth();let body=document.getElementById("commentText").value.trim();if(!body)return;let r=await db.from("comments").insert({script_id:id,user_id:user.id,body});if(r.error)return alert(r.error.message);openScript(id)}
async function loadDB(){let r=await db.from("scripts").select("*").order("created_at",{ascending:false});if(!r.error&&r.data?.length)scripts=r.data.map(s=>({id:s.id,title:s.title,game:s.game_name,tags:s.tags||[],author:s.author_id,views:s.views||0,likes:s.likes||0,verified:s.status==="approved",desc:s.description||"",code:s.script_content||s.source_url||""}));render()}
function updateUser(){userBtn.textContent=user?user.email:"Giriş / Kayıt";adminBtn.classList.toggle("hidden",user?.email?.toLowerCase()!=="mm2ultimatehub@gmail.com")}
async function openAdmin(){if(user?.email?.toLowerCase()!=="mm2ultimatehub@gmail.com")return;admin.classList.add("show");let r=await db.from("scripts").select("*").order("created_at",{ascending:false});if(r.error)return adminContent.textContent=r.error.message;adminContent.innerHTML=(r.data||[]).map(s=>'<div class="admin-row"><div><b>'+esc(s.title)+'</b><div class="status">'+esc(s.status)+' · '+esc(s.game_name)+'</div></div><div>'+(s.status==="pending"?'<button class="primary" onclick="approve(\''+s.id+'\')">Onayla</button> ':'')+'<button class="ghost" onclick="removeScript(\''+s.id+'\')">Sil</button></div></div>').join("")||"Script yok."}function hideAdmin(){admin.classList.remove("show")}async function approve(id){let r=await db.from("scripts").update({status:"approved"}).eq("id",id);if(r.error)alert(r.error.message);await openAdmin();await loadDB()}async function removeScript(id){if(!confirm("Script silinsin mi?"))return;await db.from("scripts").delete().eq("id",id);openAdmin();loadDB()}
async function boot(){let s=await db.auth.getSession();user=s.data.session?.user||null;updateUser();await loadDB();db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;updateUser()})}boot();